name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy-main-server:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to main server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          pass: ${{ secrets.PASSWORD }}
          user: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOSTNAME }}
          scp: |
            'hello' => /var/www/html
